<a href="https://colab.research.google.com/github/AbdullahRasheed452/ML-Internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [11]:
import os, subprocess

REPO_URL = "https://github.com/AbdullahRasheed452/ML-Internship"
REPO_DIR = "ML-Internship"

if not os.path.isdir(REPO_DIR):
    subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)

if os.getcwd().split("/")[-1] != REPO_DIR:
    os.chdir(REPO_DIR)

In [12]:
%pip -q install duckdb huggingface_hub

In [13]:
import os, getpass

HF_TOKEN = os.environ.get('HF_TOKEN')
if not HF_TOKEN:
    try:
        from google.colab import userdata
        HF_TOKEN = userdata.get('HF_TOKEN')
    except Exception:
        pass
HF_TOKEN = HF_TOKEN or getpass.getpass('HF_TOKEN')

In [14]:
import duckdb

con = duckdb.connect()
con.execute(f"CREATE OR REPLACE SECRET hf (TYPE huggingface, TOKEN '{HF_TOKEN}')")

REL = 'hf://datasets/FlyRank/internship-warehouse'
TABLES = {
    'dim_clients':                f"read_parquet('{REL}/dim_clients.parquet')",
    'dim_content':                f"read_parquet('{REL}/dim_content.parquet')",
    'fact_daily':                 f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')",
    'fact_daily_sample':          f"read_parquet('{REL}/fact_content_daily_performance_sample.parquet')",
    'fact_query_90d':             f"read_parquet('{REL}/fact_content_query_90d.parquet')",
}

for name, src in TABLES.items():
    n = con.sql(f'SELECT COUNT(*) FROM {src}').fetchone()[0]
    print(f'{name:22} {n:>12,} rows')

dim_clients                     104 rows
dim_content                 519,606 rows

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

fact_daily               78,835,655 rows
fact_daily_sample        11,694,072 rows
fact_query_90d            2,414,248 rows

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [15]:
# Unit of analysis: one row = one content page, for one client, on one day
# Time window: month = 2026-03 (a mid panel month, used to build and test)
# The final month, June 2026, stays sealed and untouched for now

In [16]:
grain_check = con.sql(f"""
    SELECT client_hash_id, content_hash_id, report_date, COUNT(*) as row_count
    FROM {TABLES['fact_daily']}
    WHERE report_date >= '2026-03-01' AND report_date < '2026-04-01'
    GROUP BY client_hash_id, content_hash_id, report_date
    HAVING COUNT(*) > 1
    LIMIT 5
""").df()

print(f"Rows where the grain is violated (should be empty): {len(grain_check)}")
grain_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Rows where the grain is violated (should be empty): 0

Empty DataFrame
Columns: [client_hash_id, content_hash_id, report_date, row_count]
Index: []

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [17]:
# Feature fields (things we know before making a decision, safe to use):
# gsc_impressions, gsc_clicks, gsc_avg_position, content_age_days, word_count

# Label field (the thing we want to predict):
# trend_direction, specifically whether it says "down"

# Context fields (background info, not fed into the model):
# client_hash_id, content_hash_id, report_date

# Excluded fields (left out on purpose):
# health_score, priority_score, action_type
# left out because these are the app's own decisions, not raw data
# using them would just copy the existing rules instead of learning anything new

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [18]:
# Query 1: row count and date span for our March 2026 slice
row_count_check = con.sql(f"""
    SELECT COUNT(*) AS row_count,
           MIN(report_date) AS start_date,
           MAX(report_date) AS end_date
    FROM {TABLES['fact_daily']}
    WHERE report_date >= '2026-03-01' AND report_date < '2026-04-01'
""").df()

row_count_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   row_count start_date   end_date
0    9841378 2026-03-01 2026-03-31

In [19]:
# Query 2: availability check, how many rows actually have real data
# using IS TRUE to filter only rows where GA4 data is truly available
availability_check = con.sql(f"""
    SELECT COUNT(*) AS total_rows,
           SUM(CASE WHEN ga4_data_available IS TRUE THEN 1 ELSE 0 END) AS rows_with_ga4
    FROM {TABLES['fact_daily']}
    WHERE report_date >= '2026-03-01' AND report_date < '2026-04-01'
""").df()

availability_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  rows_with_ga4
0     9841378       413966.0

In [20]:
# Results:
# March 2026 slice has 9,841,378 rows, spanning 2026-03-01 to 2026-03-31
# Out of those, only 413,966 rows actually have GA4 data available
# This shows most rows in this slice only have search data, not full
# engagement data, which is a real limit of this dataset

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [21]:
# Data limits for this slice
# Clients have unequal history, so trends are not equally reliable across clients
# Only about 4 percent of rows have GA4 data, most rows are search only
# Rows before GA4 tracking started show zero engagement, not zero real traffic

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.